### ISSUE TITLE
Adding new users doesn't seem to work

### ISSUE THREAD

**Issue by plomlompom** [DracoBlue/twtxt-registry#2]
```
$ curl -X POST https://registry.twtxt.org/api/plain/users?url=http://htwtxt.plomlompom.com/feeds/Test&nickname=Test
[1] 26131
$ `nickname` and `url` must be provided.
```

What am I doing wrong?

**Comment by DracoBlue** [comment]
Put quotationmarks around the url, since & is a special bash character ;(

Am Sonntag, 14. Februar 2016 schrieb Christian Heller :

> $ curl -X POST https://registry.twtxt.org/api/plain/users?url=http://htwtxt.plomlompom.com/feeds/Test&nickname=Test
> [1] 26131
> $ `nickname` and `url` must be provided.
> 
> What am I doing wrong?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DracoBlue/twtxt-registry/issues/2.

## 

  http://dracoblue.net

**Comment by plomlompom** [comment]
I see, the examples in the README seem buggy then.

**Comment by DracoBlue** [comment]
Fixed in README. Thx!
