### ISSUE TITLE
Format /users according to spec

### ISSUE THREAD

**Issue by mdom** [DracoBlue/twtxt-registry#4]
The specification on twtxt and the documentation here states that the first fields in the result from /users should be in twtxt's mention syntax. Currently it's the users url. I actually prefer the current format as the nicks are already listed in the third field, but in that case documentation and spec should be changed.

**Comment by kseistrup** [comment]
I would definitely prefer that nick and URL be delivered is seperate fields, rather than merged into the mention format. If I need it, I can always combine the two as `@<nick URL>`.

**Comment by mdom** [comment]
And the other api endpoints also return nick and url in a single field. It would be really nice to seperate them into their own fields. The mention syntax makes sense in a tweet text but here it makes the fields imho just harder to parse.

**Comment by DracoBlue** [comment]
I will see that I can change the spec for users. @buckket what do you think?

**Comment by buckket** [comment]
Yes, separating seems like the way to go! There is no need to make things more complicated. :+1:

**Comment by DracoBlue** [comment]
Fixed with 598d050
